config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/projects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  
  def home
  end

  def about
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#0f4898">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#2b5797">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rebecca Douglass Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'application/favicon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

  <div id="flex-content-container">

    <div class="nav-container">
      <nav class="navbar navbar-toggleable-md navbar-light bg">
      <a class="navbar-brand" href="#">Rebecca Douglass</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-auto mt-2 mt-md-0">
            <li class="nav-item">
             <a class="nav-link" <%= link_to "About", static_pages_about_path %> </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Coding", root_path %> </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Design", static_pages_projects_path %> </a> 
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>  

 
 <!-- > <div id="footer">
      <div class="container">
        <b>Footer Here</b> 
        <%= link_to 'Contact', '#' %>
        <%= link_to 'Linked In', '#' %>
        <%= link_to 'GitHub', '#' %>
      </div>
  </div> -->

  
    <%= yield %>
   </body> 


</html>

app/views/static_pages/about.html.erb
<html>
<head>
  <%# <meta name="viewport" content="width=device-width, initial-scale=1.0"> %>
  <title>About Rebecca Douglass</title>
</head>
 
  <h2 class="title">Meet Rebecca</h2>
<body>  
<div class="container about-container noshadow">
  <div class ="row no-gutter">
  <div class="col-lg-6 col-md-12 image-div">
     <%= image_tag 'Webpage-selfportrait.jpg', :class => "first-pic" %> 
    </div>
    <div class ="col-lg-6 col-md-12 about-div">

    <h5 class="about"></h5> 
     <p class = "frosty"> Creative and detailed oriented Full Stack Web Developer
      with a focus on design. Highly personable with excellent client
      and relationship building skills. Proven knack for analytical problem solving from
      her background in medicine and business. Known among colleagues for a strong work ethic that
      keeps her dedicated until the very end. Regularly complimented on verbal
      and written communication abilities.
       </p>
       <p class="frosty">
       Currently entertaining new opportunities.  Please get in touch via email:
          <a href="mailto:rebecca.s.douglass@gmail.com" class="contact-link">rebecca.s.douglass@gmail.com</a>
          <ul class="social">
            <div class="center">
              <li class="d-inline-block">
                <button type="button" class="btn3 btn-light"> <a href="https://docs.google.com/document/d/1ggKPNXDCAE5IYnmKaXLdH0m7jbySAOOBdkNq3l-ADpA/edit?usp=sharing" target="blank"> <i class="fas fa-file fa-2x"></i> </a></button> <span class=small>resume</span></li>
              <li class="d-inline-block">
                <button type="button" class="btn3 btn-light"> <a href="https://github.com/beccadouglass" target="blank"> <i class="fab fa-github fa-2x"></i> </a></button> <span class=small>github</span></li>
              <li class="d-inline-block">
                <button type="button" class="btn3 btn-light"> <a href="https://www.linkedin.com/in/rebecca-douglass-054402196/" target="blank" > <i class="fab fa-linkedin fa-2x"></i> </a></button> <span class=small>linkedin</span></li>
            </div>
          </ul>        
        </p>
    
    </div>
  
    
<!-- </div> -->
    <div class="container shadow">
    <hr>
        <p class="frosty skills no-gutter">
                    Rebecca has developed proficiency and expertise
                    in the following programming languages and
                    comfort with the following tools:</p>
                    <p align ="center">
                    <i class="fab fa-github fa-2x"></i>
                    <i class="fab fa-trello fa-2x"></i>
                    <i class="fab fa-slack fa-2x"></i>
                    <i class="fab fa-html5 fa-2x"></i>
                    <i class="fab fa-sass fa-2x"></i>
                    <i class="fab fa-css3-alt fa-2x"></i>
                    <i class="fab fa-js-square fa-2x"></i>
                    <i class="fab fa-node-js fa-2x"></i>
                    <i class="fab fa-bootstrap fa-2x"></i>
                    <i class="fab fa-wordpress fa-2x"></i>
                    <i class="fab fa-php fa-2x"></i>
                    <%# <i class="fab fa-python fa-2x"></i> %>
                    <i class="fab fa-react fa-2x"></i>
                    <i class="fab fa-adobe fa-2x"></i>
                    <i class="fab fa-sketch fa-2x"></i>
                    <br/>
                    <br/>
                    <p class="small-foot">HTML, CSS, SASS, Javascript, JQuery, ReactJS, NodeJS, PHP, Ruby, Ruby on Rails, Bootstrap, Flexbox, CSS-Grid, PosgreSQL, Wordpress, Github, Vagrant, Adobe, Sketch</p>
<hr>
                  </p>
                  
      </div>
    </div>
  </div>

</div>
<div>
<p>
<br/>
<br/>
</p>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<html>
<head>
<body>
<h2 class="title">Meet Rebecca</h2>
<body>  
<div class="container about-container">
  <div class ="row no-gutter">
  <div class="col-lg-6 col-md-12 image-div">
     <%= image_tag 'Webpage-selfportrait.jpg', :class => "first-pic" %> 
    </div>
    <div class ="col-lg-6 col-md-12 about-div">

    <h5 class="about"></h5> 
     <p class = "frosty"> Creative and detailed oriented Full Stack Web Developer
      with a focus on UX design. Highly personable with excellent client
      and relationship building skills. Proven knack for analytical problem solving from
      her background in medicine and business. Known among colleagues for a strong work ethic that
      keeps her dedicated until the very end. Regularly complimented on verbal
      and written communication abilities.
       </p>
       <p class="frosty">
       Currently entertaining new opportunities.  Please get in touch via email:
          <a href="mailto:rebecca.s.douglass@gmail.com" class="contact-link">rebecca.s.douglass@gmail.com</a>
          <ul class="social">
            <div class="center">
              <li class="d-inline-block">
                <button type="button" class="btn btn-outline-dark"> <a href="https://docs.google.com/document/d/1ggKPNXDCAE5IYnmKaXLdH0m7jbySAOOBdkNq3l-ADpA/edit?usp=sharing" target="blank"> <i class="fas fa-file fa-2x"></i> </a></button> <span class=small>resume</span></li>
              <li class="d-inline-block">
                <button type="button" class="btn btn-outline-dark"> <a href="https://github.com/beccadouglass" target="blank"> <i class="fab fa-github fa-2x"></i> </a></button> <span class=small>github</span></li>
              <li class="d-inline-block">
                <button type="button" class="btn btn-outline-dark"> <a href="https://www.linkedin.com/in/rebecca-douglass-054402196/" target="blank" > <i class="fab fa-linkedin fa-2x"></i> </a></button> <span class=small>linkedin</span></li>
            </div>
          </ul>        
        </p>
    
    </div>
  
    
<!-- </div> -->
    <div class="container">
    <hr>
        <p class="frosty skills no-gutter">
                    Rebecca has developed proficiency and expertise
                    in the following programming languages and
                    comfort with the following tools:</p>
                    <p align ="center">
                    <i class="fab fa-github fa-2x"></i>
                    <i class="fab fa-trello fa-2x"></i>
                    <i class="fab fa-slack fa-2x"></i>
                    <i class="fab fa-html5 fa-2x"></i>
                    <i class="fab fa-sass fa-2x"></i>
                    <i class="fab fa-css3-alt fa-2x"></i>
                    <i class="fab fa-js-square fa-2x"></i>
                    <i class="fab fa-bootstrap fa-2x"></i>
                    <i class="fab fa-wordpress fa-2x"></i>
                    <i class="fab fa-python fa-2x"></i>
                    <i class="fab fa-adobe fa-2x"></i>
                    <i class="fab fa-sketch fa-2x"></i>
                    <br/>
                    <br/>
<hr>
                  </p>
      </div>
    </div>
  </div>

</div>
<div>
<p>
<br/>
<br/>
</p>
</div>
</body>
</html>


<%# Card Code %>

  <div class="col-lg-6 col-md-12">

    <div class="card mx-auto">
      <a href="https://mello-rebecca-douglass.herokuapp.com/boards">
        <%= image_tag 'Melloboard.png', class: 'card-img-top' %> </a>
        <div class="card-body">
          <h5 class="card-title">Mello</h5>
          <p class="card-text">Boards, lists, and cards organizer app that
              allows you to prioritize work, family or personal projects.
              Features a fluid user interface by using JavaScript and JQuery. It
              allows users to rapidly add dynamic content.
            <div class="project-link">
              <button type="button" class="btn btn-light"> <a href="https://github.com/beccadouglass/mello-fullstack" target="blank"> GitHub</a> </button>
              <button type="button" class="btn btn-light"> <a href="https://mello-rebecca-douglass.herokuapp.com/boards" target="blank"> Heroku</a> </button>
            </div>
           <!-- > <div class ="card-footer">
              <a href=https://github.com/beccadouglass/mello-fullstack class="link-size" target="blank">https://github.com/beccadouglass/mello-fullstack
                </a> <a
                href=https://mello-rebecca-douglass.herokuapp.com/boards class="link-size" target="blank">https://mello-rebecca-douglass.herokuapp.com/boards
                </a>
                <br> 
            </div> -->
          </p>
        </div>
    </div>
  </div>
</div>
</div>

<div class="col-lg-6 col-md-12">
    <div class="card mx-auto">
      <a href="https://shopper-rebecca-douglass.herokuapp.com">
      <%= image_tag 'shopper.png', class: 'card-img-top' %> </a>
      <div class="card-body">
        <h5 class="card-title">Shopper</h5>
        <p class="card-text">Simple ecommerce site developed solely by Rebecca that
         allows signed in users to add products
         to cart and checkout with Stripe API.  
         Also new products can be added by administration as they become available.
         
          <div class="project-link">
              <button type="button"class="btn btn-light"> <a href="https://github.com/beccadouglass/shopper" target="blank"> GitHub</a> </button>
              <button type="button"class="btn btn-light"> <a href="https://shopper-rebecca-douglass.herokuapp.com" target="blank"> Heroku</a> </button>
          </div> 
             <div class ="card-footer">
                <a href=https://github.com/beccadouglass/shopper class="link-size" target="blank">https://github.com/beccadouglass/shopper </a> 
                <a href=https://shopper-rebecca-douglass.herokuapp.com class="link-size" target="blank">https://shopper-rebecca-douglass.herokuapp.com
                </a>
              </div>
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-6 col-md-12">  
    <div class="card mx-auto">
      <a href="https://nomster-becca-douglass.herokuapp.com">
        <%= image_tag 'nomster1.png', class: 'card-img-top' %> </a>
      <div class="card-body">
        <h5 class="card-title">Inquest</h5>
        <p class="card-text">A Yelp clone that integrates with the Google Maps API
      and includes features like user comments, star ratings,
      image uploading, and user authentication.  Checkout restaurants in Jackson, Wyoming through this app.
          <div class="project-link">
            <button type="button" class="btn btn-light"> <a href="https://github.com/beccadouglass/nomster" target="blank">GitHub</a> </button>
            <button type="button" class="btn btn-light"> <a href="https://nomster-becca-douglass.herokuapp.com" target="blank">Heroku</a> </button>
          </div>
         <!-- <div class ="card-footer">
            <a href=https://github.com/beccadouglass/nomster class="link-size" target="blank">https://github.com/beccadouglass/nomster </a> 
            <a href=https://nomster-becca-douglass.herokuapp.com class="link-size" target="blank">https://nomster-becca-douglass.herokuapp.com
        </a>
          </div> -->
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-6 col-md-12">
    <div class="card mx-auto">
      <a href="https://flixter-beccadouglass.herokuapp.com">
        <%= image_tag 'flixter1.png', class: 'card-img-top' %> </a>
      <div class="card-body">
        <h5 class="card-title">Flixter</h5>
        <p class="card-text">A educational ecourse with two sided, video streaming marketplace platform that
          features credit card payment capabilities, user role
          management, complex user interfaces, and advanced
          database relationships. 
          <div class="project-link">
            <button type="button" class="btn btn-light"> <a href="https://github.com/beccadouglass/flixter" target="blank"> GitHub</a> </button>
            <button type="button" class="btn btn-light"> <a href="https://flixter-beccadouglass.herokuapp.com" target="blank"> Heroku</a> </button>
          </div>
           <!-- <div class ="card-footer">
              <a href=https://github.com/beccadouglass/flixter class="link-size" target="blank">https://github.com/beccadouglass/flixter </a> 
              <a href=https://flixter-beccadouglass.herokuapp.com class="link-size" target="blank">https://flixter-beccadouglass.herokuapp.com
              </a> 
            </div> -->
        </p>
      </div>
    </div>
  </div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%# <meta name="viewport" content="width=device-width, initial-scale=1.0"> %>
    <title>Coding by Rebecca Douglass</title>
    <link rel="shortcut icon" type="image/png" href="img/rfslogo.png">

  </head>
  <h2 class="title">Coding Projects</h2>

<body>

<%# GRID CONTAINERS %>

<div class="containergrid">

    <section class="designs">
        <div class="design">
            <%= image_tag 'flashcards.png', :class => "design__img" %>
            <h5 class="design__name">Flashcards</h5>
            <%# <div class="design__pics">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-images fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Pics</p>
            </div>
            <div class="design__video">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-video fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Video</p>
            </div> %>
            <div class="design__git">
                <div class="design__sprite">
                <a href="https://github.com/beccadouglass/flashcards" target="blank"><i class="fab fa-github fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Code</p>
            </div>
            <%# <div class="design__web">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-globe fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Website</p>
            </div> %>
            <div class="design__bottom">Javascript and ReactJS.  Flip through cards to test your knowledge in React history.
              Click cards to flip and see answer on back.</div>
        </div>
        

        <div class="design">
            <%= image_tag 'shopper.png', :class => "design__img" %>
            <h5 class="design__name">Chestnut Feather</h5>
            <%# <div class="design__pics">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-images fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Pics</p>
            </div>
            <div class="design__video">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-video fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Video</p>
            </div>  %>
            
            <div class="design__git">
                <div class="design__sprite">
                <a href="https://github.com/beccadouglass/shopper" target="blank"><i class="fab fa-github fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Code</p>
            </div>
            <div class="design__web">
                <div class="design__sprite">
                <a href="https://shopper-rebecca-douglass.herokuapp.com" target="blank"><i class="fas fa-globe fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Website</p>
            </div>
            <div class="design__bottom">Simple ecommerce site developed solely by Rebecca that
         allows signed in users to add products
         to cart and checkout with Stripe API.  
         Also new products can be added by administration as they become available.</div>
        </div>

        <div class="design">
            <%= image_tag 'rfs-screen2.png', :class => "design__img"%>
            <h5 class="design__name">Reflections From The Saddle</h5>
            <%# <div class="design__pics">
                <div class="design__sprite">
                <a href="#"> <i class="fas fa-images fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Pics</p>
            </div>
            <div class="design__video">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-video fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Video</p>
            </div> %>
            <div class="design__git">
                <div class="design__sprite">
                <a href="https://github.com/beccadouglass/wordpressrfs" target="blank"><i class="fab fa-github fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Code</p>
            </div>
            <%# <div class="design__web">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-globe fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Website</p>
            </div> %>
            <div class="design__bottom">Advanced CSS, SASS, PHP, Wordpress. Blog site with e-learning platform.  Still being developed.  Check back for updates.</div>
        </div>

        <div class="design">
            <%= image_tag 'nomster1.png', :class => "design__img"%>
            <h5 class="design__name">Nomster</h5>
            <%# <div class="design__pics">
                <div class="design__sprite">
                <a href="#"> <i class="fas fa-images fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Pics</p>
            </div>
            <div class="design__video">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-video fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Video</p>
            </div> %>
            
            <div class="design__git">
                <div class="design__sprite">
                <a href="https://github.com/beccadouglass/nomster" target="blank"><i class="fab fa-github fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Code</p>
            </div>
            <div class="design__web">
                <div class="design__sprite">
                <a href="https://nomster-becca-douglass.herokuapp.com" target="blank"><i class="fas fa-globe fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Website</p>
            </div>
            <div class="design__bottom">Ruby on Rails.  A Yelp clone that integrates with the Google Maps API
      and includes features like user comments, star ratings,
      image uploading, and user authentication.  Checkout restaurants in Jackson, Wyoming through this app.</div>
        </div>

        <div class="design">
            <%= image_tag 'flixter1.png', :class => "design__img"%>
            <h5 class="design__name">Flixter</h5>
            <%# <div class="design__pics">
                <div class="design__sprite">
                <a href="#"> <i class="fas fa-images fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Pics</p>
            </div>
            <div class="design__video">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-video fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Video</p>
            </div> %>
            <div class="design__git">
                <div class="design__sprite">
                <a href="https://github.com/beccadouglass/flixter" target="blank"><i class="fab fa-github fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Code</p>
            </div>
            <div class="design__web">
                <div class="design__sprite">
                <a href="https://flixter-beccadouglass.herokuapp.com" target="blank"><i class="fas fa-globe fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Website</p>
            </div>
            <div class="design__bottom">Ruby on Rails.  A educational ecourse with two sided, video streaming marketplace platform that
          features credit card payment capabilities, user role
          management, complex user interfaces, and advanced
          database relationships. </div>
        </div>

        <div class="design">
            <%= image_tag 'Melloboard.png', :class => "design__img"%>
            <h5 class="design__name">Mello</h5>
            <%# <div class="design__pics">
                <div class="design__sprite">
                <a href="#"> <i class="fas fa-images fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Pics</p>
            </div>
            <div class="design__video">
                <div class="design__sprite">
                <a href="#"><i class="fas fa-video fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Video</p>
            </div> %>
            <div class="design__git">
                <div class="design__sprite">
                <a href="https://github.com/beccadouglass/mello-fullstack" target="blank"><i class="fab fa-github fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Code</p>
            </div>
            <div class="design__web">
                <div class="design__sprite">
                <a href="https://mello-rebecca-douglass.herokuapp.com/boards" target="blank"><i class="fas fa-globe fa-2x btn3"></i></a>
                </div>
                <p class="fas_label">Website</p>
            </div>
            <div class="design__bottom">Javascript and JQuery.  Boards, lists, and cards organizer app that
              allows you to prioritize work, family or personal projects.  Allows users to rapidly add dynamic content. </div>
        </div>
    </section>

  </div>

  <h2 class='title'>Coding Snippets</h2>
    <div class="container shadow">
    <div class ="row no-gutter">
        <div class ="col">
            <h4>Temperature Conversion</h4>
            <p>This ruby program will prompt the user for a temperature in degrees Celsius and let the user know
          what the corresponding termperature is in Fahrenheit.
            </p>
          
      <pre><code class="language-ruby coding-example">
#code without using method
puts &quot;Enter today's temperature
in celsius&quot;
celsius = gets.chomp
val = celsius.to_i * 1.8 + 32
puts val

# code using method
puts &quot;Enter today's temperature
in celsius&quot;
celsius = gets.chomp
val = celsius.to_i
def conversion(number)
    return (number * 1.8) + 32
    end
puts conversion(val)
</code></pre>
    </div>
  </div>
</div>
<br class="clear" />

  <div class="container shadow">
    <div class ="row no-gutter">
        <div class ="col">
        <h4>Ordinal Challenge</h4>
          <p>This Ruby program will convert a plain number to the ordinal number. So for example, if the user
          enters 2, it will display 2nd, if the user enters 3, it will display 3rd, etc </p>

        <pre><code class="language-ruby coding-example">
puts &quot;Enter a number:&quot;
number = gets.chomp
val = number.to_i

ord =  val % 10 
ordsecond = val % 100

if number == &quot;11&quot; || number == &quot;12&quot;
|| number == &quot;13&quot;
puts &quot;That's the #{number}th item&quot;
elsif ord == 1 
puts &quot;That's the #{number}st item&quot;
elsif ord == 1 &amp;&amp; ordsecond == 1
puts &quot;That's the #{number}th item&quot;
elsif ord == 2 &amp;&amp; ordsecond != 1
puts &quot;That's the #{number}nd item&quot;
elsif ord == 3 
puts &quot;That's the #{number}rd item&quot;
else
puts &quot;That's the #{number}th item&quot;
end
      </code></pre>
    </div>  
  </div>
</div>
<br class="clear" />

<div class="container shadow">
  <div class ="row no-gutter">
      <div class ="col">
      <h4>Foobar</h4>
        <p>This Ruby program is an adaptation of a classic technical interview problem which displays
        sequences of the Foobar pattern.</p>
   
      <pre><code class="language-ruby coding-example">
puts &quot;How many items they want to see?&quot;
items = gets.chomp.to_i
numbers = (1..items)
numbers.each do |num|

if num % 3 == 0 &amp;&amp; num % 5 == 0
puts &quot;FooBar&quot;
elsif num % 3 == 0
puts &quot;Foo&quot;
elsif num % 5 == 0
puts &quot;Bar&quot;
else
puts num
end
end
      </code></pre>
    </div>
  </div>
</div>
<p>
<br/>
<br/>
</p>
</body>

</html>